from tkinter import*
root=Tk()
root.geometry("600x400")
def si():
    p=int(principalentry.get())
    r=int(rateentry.get())
    t=int(timeentry.get())
    s=(p*r*t)/100
    Label(f1,text=f"{int(s)}",font="aerial 10 bold").grid(row=5,column=2)
def ci():
    p=int(principalentry.get())
    r=int(rateentry.get())
    t=int(timeentry.get())
    c=(p*((1+r/100)**t))-p
    Label(f1,text=f"{int(c)}",font="aerial 10 bold").grid(row=6,column=2)


f1=Frame(root,bg="grey",padx=10,pady=30,relief="groove",border=10)#f1.grid(row=50,column=6)
f1.place(relx=0.5, rely=0.5, anchor=CENTER)
Label(f1,text="INTEREST CALCULATOR",background="grey",font="comicsansns 15 bold",padx=5,pady=8,border=5,relief="sunken").grid(row=0,column=2)
principal=Label(f1,text="Principal",pady=1,font="aerial 10 bold")
rate=Label(f1,text="Rate(%)",pady=1,font="aerial 10 bold")
time=Label(f1,text="Time(in years)",pady=1,font="aerial 10 bold")
simpleinterest=Label(f1,text="Simple Interest",pady=1,font="aerial 10 bold")
compoundinterest=Label(f1,text="Compound Interest",pady=1,font="aerial 10 bold")
principal.grid(row=1,column=0)
rate.grid(row=2,column=0)
time.grid(row=3,column=0)
simpleinterest.grid(row=5,column=0)
compoundinterest.grid(row=6,column=0)
principalvalue=StringVar()
ratevalue=StringVar()
timevalue=StringVar()
simplevalue=StringVar()
complexvalue=StringVar()
principalentry=Entry(f1,textvariable=principalvalue,font="aerial 10 bold")
rateentry=Entry(f1,textvariable=ratevalue,font="aerial 10 bold")
timeentry=Entry(f1,textvariable=timevalue,font="aerial 10 bold")
simpleentry=Entry(f1,textvariable=simplevalue,font="aerial 10 bold")
complexentry=Entry(f1,textvariable=complexvalue,font="aerial 10 bold")
principalentry.grid(row=1,column=2,pady=5)
rateentry.grid(row=2,column=2,pady=5)
timeentry.grid(row=3,column=2,pady=5)
simpleentry.grid(row=5,column=2,pady=5)
complexentry.grid(row=6,column=2,pady=5)
Button(f1,text="Simple Interest",command=si,font="aerial 10 bold").grid(row=5,column=3)
Button(f1,text="Compound Interest",command=ci,font="aerial 10 bold").grid(row=6,column=3)
root.mainloop()
